### ISSUE TITLE
Not working with cljx?

### ISSUE THREAD

**Issue by jeroenvandijk** [zcaudate/lein-repack#5]
Hi Chris,

I'm using Prismatic Schema in the project I'm using lein-repack for. It seems that `lein-repack` is not picking up the dependency of `schema` although it is in the list of `:dependencies` and `:require`. My hypothesis is that this is due to the fact that Schema [uses cljx](https://github.com/Prismatic/schema/blob/master/src/cljx/schema/core.cljx). Does that make sense?

I'm working around it by doing an `:aot` of the project. This also helps for another dependency on a maven project (using `:import`). I had to put the `:aot` in a seperate profile to prevent repack from adding it to the generated project.clj. This is what I did it in the `project.clj`:

```clojure
:aliases {"pack"
           ["do" "with-profile" "pre-compile" "compile," "repack" "install"]
           }
:profiles {
            :pre-compile
            {:aot :all}
...
}
```

The pre-compiling in the normal project makes sure that both the java dependencies and the schema dependency can be used for compilation. Repack then doesn't have to compile those namespaces anymore (which would fail otherwise) and can happily package the projects.

Cheers,
Jeroen

**Comment by zcaudate** [comment]
I've decided to close this issue for now.... after the 0.2.5 rewrite, clix files may be supported if someone has time to write an analyser for it. I'm not keen to do this as I'd rather use lein-dalap for source transformation but if anyone wants to have a go at it, there are samples for cli, cljs and java here:
https://github.com/zcaudate/lein-repack/tree/master/src/leiningen/repack/analyser
