### ISSUE TITLE
Doesn't work well with project that have a name without a /

### ISSUE THREAD

**Issue by RyanMcG** [zcaudate/lein-repack#6]
If the project name is `blarg`, then the group id is `blarg` and the artifcat id is `blarg`. It seems that parts of *repack* thinks the `blarg.foo` library has the group id of `blarg.foo` and other parts think it is `blarg` (compiled assets use `blarg.foo` but generated `project.clj`s think it is `blarg`).

Modifying `project.clj` so that the project name is `blarg/blarg` instead of `blarg` fixes the issue.

I can probably submit a PR for this but I need to get approval first.

**Comment by zcaudate** [comment]
This has been fixed
