### ISSUE TITLE
Non-source files in source directory produce unwanted branches

### ISSUE THREAD

**Issue by RyanMcG** [zcaudate/lein-repack#9]
Running `lein repack manifest` results in the following. Note the branch keyed with `".context.clj"`.

```
{:root
 {:files [],
  :dependencies
  [[org.clojure/clojure "1.6.0"]
   [mvxcvi/puget "0.6.4"]
   [mvxcvi/whidbey "0.4.1"]
   [fixturex/fixturex.context "0.2.1"]
   [fixturex/fixturex.core "0.2.1"]
   [fixturex/fixturex.higher "0.2.1"]
   [fixturex/fixturex..context.clj "0.2.1"]],
  :version "0.2.1",
  :group "fixturex",
  :name "fixturex"},
 :branches
 {".context.clj"
  {:coordinate [fixturex/fixturex..context.clj "0.2.1"],
   :files ["src/fixturex/.context.clj.swp"],
   :dependencies [[org.clojure/clojure "1.6.0"]],
   :version "0.2.1",
   :name "fixturex/fixturex..context.clj",
   :group "fixturex"},
  "higher"
  {:coordinate [fixturex/fixturex.higher "0.2.1"],
   :files ["src/fixturex/higher.clj"],
   :dependencies [[org.clojure/clojure "1.6.0"]],
   :version "0.2.1",
   :name "fixturex/fixturex.higher",
   :group "fixturex"},
  "core"
  {:coordinate [fixturex/fixturex.core "0.2.1"],
   :files ["src/fixturex/core.clj"],
   :dependencies [[org.clojure/clojure "1.6.0"]],
   :version "0.2.1",
   :name "fixturex/fixturex.core",
   :group "fixturex"},
  "context"
  {:coordinate [fixturex/fixturex.context "0.2.1"],
   :files ["src/fixturex/context.clj"],
   :dependencies
   [[org.clojure/clojure "1.6.0"] [fixturex/fixturex.higher "0.2.1"]],
   :version "0.2.1",
   :name "fixturex/fixturex.context",
   :group "fixturex"}}}
```

I propose we whitelist files by extension with some reasonable defaults which may be overridden by the user. This way we would avoid editor files from vim and emacs.

**Comment by zcaudate** [comment]
I'm going to be cheeky and say that you shouldn't be putting non-source files in your source directory in the first place. I'll close this issue for now but will probably be looking at a similar issue for https://github.com/zcaudate/lein-repack/issues/14

**Comment by RyanMcG** [comment]
Ha. Vim creates files that end in swp and swo by default. I think emacs might create files that end in ~. Perhaps other editors produce similar crap.

**Comment by zcaudate** [comment]
Hmmm... That is a problem :)

I'm thinking the best way would be to specify what files to ignore in the config.

**Comment by RyanMcG** [comment]
If I am reading this correctly, leiningen ignores hidden files when creating jars.

https://github.com/technomancy/leiningen/blob/6b8e74eaeeeb91cb3bb6467a14b5ec827b771dfb/leiningen-core/src/leiningen/core/project.clj#L213

This seems like a sensible default. Why not just use jar exclusions from project.clj?

**Comment by zcaudate** [comment]
Yep. That's a great idea.

**Comment by zcaudate** [comment]
Okay, this feature has been added in 0.2.10. You can leave it as default or specify :jar-exclusion for each entry in the `:repack` configuration.
